/* VenuePlus — Agent Operations Manual data.
   14 agents across 5 facet groups. Autonomy follows the "balanced" policy:
   agents draft everything; the operator approves anything outbound,
   customer-facing, financial, or legal. Money movement & legal are hard-gated. */
(function () {
  // autonomy badge kinds → token-driven colors (see styles.css)
  // auto (green) · draft (amber) · gated (orange) · hardgate (red)
  const FACETS = [
    { id: 'supply-growth',  name: 'Supply Growth',        color: 'var(--primary-500)', soft: 'var(--primary-50)',  blurb: 'Find and recruit new venues & service providers.' },
    { id: 'demand-growth',  name: 'Demand Growth',        color: 'var(--accent-600)',  soft: 'var(--accent-50)',   blurb: 'Generate renter demand across SEO, social & lifecycle.' },
    { id: 'onboarding-net', name: 'Onboarding & Network', color: '#15803d',            soft: '#dcfce7',            blurb: 'Get supply live and keep every booking serviceable.' },
    { id: 'operations',     name: 'Marketplace Operations', color: '#1d4ed8',          soft: '#dbeafe',            blurb: 'Run bookings, trust & safety, and the money.' },
    { id: 'customer-plat',  name: 'Customer & Platform',  color: '#7e22ce',            soft: '#f3e8ff',            blurb: 'Support every party; watch the whole system.' },
  ];

  // autonomy: 'auto' | 'draft' | 'gated' | 'hardgate'
  const A = {
    auto:     { label: 'Autonomous',         kind: 'auto',     note: 'Acts alone (read / internal writes).' },
    draft:    { label: 'Drafts → you approve', kind: 'draft',  note: 'Drafts everything; outbound / customer-facing needs approval.' },
    gated:    { label: 'Approval-gated',      kind: 'gated',    note: 'Consequential actions need your sign-off.' },
    hardgate: { label: 'Hard gate · money',   kind: 'hardgate', note: 'All money movement requires explicit approval.' },
  };

  const AGENTS = [
    /* ---------------- Supply Growth ---------------- */
    {
      id: 'discovery', name: 'Discovery', facet: 'supply-growth', autonomy: 'auto',
      mandate: 'Continuously find new commercial spaces and service providers worth recruiting.',
      responsibilities: [
        'Scan Google Places, Yelp, Instagram & commercial listing sites for candidate venues and providers.',
        'Maintain supply coverage targets by city and by venue / service category.',
        'Detect and skip entities already in the marketplace (dedupe at the source).',
        'Prioritize discovery where demand outpaces available supply.',
        'Feed a clean stream of raw leads to Enrichment.',
      ],
      tasks: [
        'Run scheduled geo-sweeps for each launch city.',
        'Pull only listings created or changed since the last crawl.',
        'Tag every lead with type (rooftop, warehouse, field…) or service category.',
        'Queue qualified raw leads for enrichment.',
        'Log coverage and source-health stats.',
      ],
      tools: ['Google Places API', 'Yelp Fusion', 'Instagram location search', 'Leads DB', 'Dedupe service'],
      autonomyNote: 'Fully autonomous — read-only collection, no outbound contact. Writes leads to the internal DB without approval.',
      escalations: [
        'A city\u2019s supply coverage drops below target.',
        'A data source rate-limits or breaks.',
        'Zero new leads found in a category for 7+ days.',
      ],
      kpis: ['New qualified leads / week', 'City coverage %', 'Duplicate rate', 'Source uptime'],
      handoffs: '→ Enrichment',
    },
    {
      id: 'enrichment', name: 'Enrichment', facet: 'supply-growth', autonomy: 'auto',
      mandate: 'Turn raw leads into complete, contactable, deduplicated records.',
      responsibilities: [
        'Resolve owner / manager emails and phone numbers.',
        'Attach social handles, websites, and firmographic detail.',
        'Verify email deliverability before anything is queued for outreach.',
        'Merge duplicates across sources into a single record.',
        'Fill missing attributes — capacity, type, operating hours.',
      ],
      tasks: [
        'Run Hunter.io email lookups for each lead.',
        'Score deliverability / bounce risk.',
        'Enrich firmographics and category metadata.',
        'Collapse duplicate leads.',
        'Write the enriched record back to the leads DB.',
      ],
      tools: ['Hunter.io', 'Email verification API', 'Enrichment provider', 'Leads DB'],
      autonomyNote: 'Fully autonomous — read / enrich / internal-write only. No outbound contact.',
      escalations: [
        'Batch deliverability is poor.',
        'An enrichment provider quota is exhausted.',
        'A lead has no contactable channel at all.',
      ],
      kpis: ['Contactable rate', 'Email verification accuracy', 'Enrichment cost / lead', 'Duplicates merged'],
      handoffs: '← Discovery   → Scoring',
    },
    {
      id: 'scoring', name: 'Scoring', facet: 'supply-growth', autonomy: 'auto',
      mandate: 'Rank every lead 0–100 so outreach effort goes where it converts.',
      responsibilities: [
        'Score leads on fit, demand match, reachability, and revenue potential.',
        'Auto-queue strong leads (≥ 60) for outreach.',
        'Suppress weak or poor-fit leads.',
        'Recalibrate the model against real booking outcomes.',
        'Keep the score distribution healthy and explainable.',
      ],
      tasks: [
        'Compute lead scores nightly.',
        'Segment leads into hot / warm / cold tiers.',
        'Push hot leads to the Outreach queue.',
        'Report score distribution to Mission Control.',
        'Retrain weights on closed-won data.',
      ],
      tools: ['Scoring model', 'Bookings / outcomes DB', 'Feature store'],
      autonomyNote: 'Autonomous for compute & queueing. Changing the auto-queue threshold (the ≥ 60 bar) requires your approval.',
      escalations: [
        'Conversion of "hot" leads drops (score drift).',
        'You would need to change the auto-queue threshold.',
        'An entire segment scores uniformly low.',
      ],
      kpis: ['Hot-lead conversion', 'Score → booking correlation', 'Queue volume', 'Model drift'],
      handoffs: '← Enrichment   → Outreach',
    },
    {
      id: 'outreach', name: 'Outreach', facet: 'supply-growth', autonomy: 'draft',
      mandate: 'Win new venues and providers through personalized, on-brand cold outreach.',
      responsibilities: [
        'Draft tailored cold emails per lead with Claude.',
        'Sequence intelligent follow-ups.',
        'Personalize by venue type and local demand signals.',
        'A/B test angles and subject lines.',
        'Never contact opted-out or suppressed leads.',
      ],
      tasks: [
        'Generate drafts for the hot-lead queue.',
        'Assemble multi-step follow-up sequences.',
        'Submit every outbound send for your approval.',
        'Record replies and auto-pause on response.',
        'Hand interested leads to Onboarding.',
      ],
      tools: ['Claude', 'Email send service', 'Suppression list', 'CRM'],
      autonomyNote: 'Drafts everything autonomously; every outbound email requires your approval. Auto-pauses a sequence the moment a lead replies.',
      escalations: [
        'Every first-touch send (approval).',
        'Negative or complaint replies.',
        'Opt-out / spam reports.',
        'A lead requesting a call.',
      ],
      kpis: ['Reply rate', 'Positive-reply rate', 'Venues / providers signed', 'Spam-complaint rate'],
      handoffs: '← Scoring   → Onboarding',
    },

    /* ---------------- Demand Growth ---------------- */
    {
      id: 'seo', name: 'SEO & Content', facet: 'demand-growth', autonomy: 'draft',
      mandate: 'Grow organic demand with venue listing pages and helpful local content.',
      responsibilities: [
        'Generate and maintain SEO listing pages per venue, city, and type.',
        'Write blog and guide content around local event search intent.',
        'Manage metadata, schema, and internal linking.',
        'Track keyword rankings and refresh stale pages.',
        'Protect against thin or duplicate content.',
      ],
      tasks: [
        'Draft new landing pages from venue data.',
        'Produce meta titles and descriptions within limits.',
        'Build topical guides ("rooftop venues in Nashville").',
        'Queue pages for publish approval.',
        'Monitor keyword positions in Search Console.',
      ],
      tools: ['Claude', 'CMS / Next.js content', 'Search Console', 'Keyword API', 'Schema generator'],
      autonomyNote: 'Drafts everything; publishing live pages or content requires your approval. Metadata tweaks to already-live pages run automatically.',
      escalations: [
        'First publish of a content batch.',
        'Ranking drops on priority terms.',
        'Indexing errors.',
        'Thin / duplicate-content risk detected.',
      ],
      kpis: ['Organic sessions', 'Indexed pages', 'Top-10 keywords', 'Page → booking rate'],
      handoffs: '→ Campaign   ← Monitor',
    },
    {
      id: 'social', name: 'Social Media', facet: 'demand-growth', autonomy: 'draft',
      mandate: 'Build brand presence and demand across social channels.',
      responsibilities: [
        'Draft Facebook & Instagram posts featuring venues and events.',
        'Maintain a content calendar with consistent cadence.',
        'Draft replies to comments and DMs.',
        'Spotlight new and featured listings.',
        'Keep voice and visuals on-brand.',
      ],
      tasks: [
        'Generate weekly post drafts with imagery.',
        'Schedule the content calendar.',
        'Draft replies to inbound comments / DMs.',
        'Flag user content worth resharing.',
        'Route support-type DMs to Support.',
      ],
      tools: ['Claude', 'Meta Graph API', 'Asset library', 'Scheduler'],
      autonomyNote: 'Drafts everything; every public post and public reply requires your approval.',
      escalations: [
        'Each post and reply (approval).',
        'Negative public comments or PR-sensitive mentions.',
        'DMs that are really support or safety issues.',
      ],
      kpis: ['Reach', 'Engagement rate', 'Follower growth', 'Social → site clicks'],
      handoffs: '→ Support',
    },
    {
      id: 'campaign', name: 'Lifecycle Campaigns', facet: 'demand-growth', autonomy: 'draft',
      mandate: 'Convert and retain venues, providers, and renters with lifecycle email & SMS.',
      responsibilities: [
        'Run drip sequences — welcome, activation, win-back.',
        'Segment audiences by role and behavior.',
        'Trigger behavior-based messages.',
        'Suppress over-mailing and respect frequency caps.',
        'Measure incremental lift, not just opens.',
      ],
      tasks: [
        'Enroll users into the right journeys.',
        'Draft each step of every sequence.',
        'Submit customer sends for approval.',
        'Prune unengaged contacts.',
        'Report cohort performance.',
      ],
      tools: ['Claude', 'ESP (drip)', 'Segmentation DB', 'Analytics'],
      autonomyNote: 'Drafts journeys and content; campaign sends to customers require your approval. Auto-suppression and journey exits are automatic.',
      escalations: [
        'New campaign launch.',
        'Unsubscribe spikes.',
        'Deliverability drops.',
        'A key segment going stale.',
      ],
      kpis: ['Activation rate', 'Repeat-booking rate', 'Win-back / churn', 'Unsubscribe rate'],
      handoffs: '← SEO   ← Onboarding',
    },

    /* ---------------- Onboarding & Network ---------------- */
    {
      id: 'onboarding', name: 'Onboarding', facet: 'onboarding-net', autonomy: 'draft',
      mandate: 'Get signed venues and providers fully live, fast — complete, priced, and bookable.',
      responsibilities: [
        'Guide new hosts / providers through profile, photos, pricing, and availability.',
        'Apply required-service rules to each new venue.',
        'Validate listing completeness before activation.',
        'Set fair starting prices from local comparables.',
        'Schedule first-listing check-ins and unblock stalled setups.',
      ],
      tasks: [
        'Send tailored setup checklists.',
        'Draft profile copy from host inputs.',
        'Suggest pricing from local comps.',
        'Verify photos, capacity, and availability.',
        'Flip completed listings to active (on approval).',
      ],
      tools: ['Claude', 'Listings DB', 'Pricing-comps engine', 'Media validation', 'Email'],
      autonomyNote: 'Drafts profiles & pricing; activating a listing and any host-facing message require your approval. Internal completeness checks are automatic.',
      escalations: [
        'A listing stalls for more than 7 days.',
        'Missing legal or insurance documents.',
        'Pricing far outside local comps.',
        'A host requesting hands-on help.',
      ],
      kpis: ['Time-to-active', 'Listing completeness %', 'Time to first booking', 'Activation rate'],
      handoffs: '← Outreach   → Network   → Trust & Safety   → Campaign',
    },
    {
      id: 'network', name: 'Provider Network', facet: 'onboarding-net', autonomy: 'draft',
      mandate: 'Ensure every booking can be fully serviced — the right providers, available, in range.',
      responsibilities: [
        'Map provider coverage by category, geography, and capacity.',
        'Detect service gaps before they block bookings.',
        'Match required services to each booking.',
        'Balance load fairly across providers.',
        'Signal Discovery where coverage is thin.',
      ],
      tasks: [
        'Maintain the live coverage map.',
        'Auto-match providers to new bookings.',
        'Rank providers by rating, proximity, and price.',
        'Flag unserviceable areas and categories.',
        'Draft and dispatch service requests (on approval).',
      ],
      tools: ['Coverage / geo engine', 'Providers DB', 'Bookings DB', 'Ranking model'],
      autonomyNote: 'Auto-matches and ranks; dispatching a paid service request to a provider requires your approval (it is outbound + financial). Coverage analysis is automatic.',
      escalations: [
        'A booking is unserviceable (no provider).',
        'Single-provider dependency in a category / city.',
        'A provider repeatedly declining.',
        'A coverage gap in a growth market.',
      ],
      kpis: ['% bookings fully serviced', 'Unserviceable count', 'Match acceptance rate', 'Provider utilization'],
      handoffs: '← Onboarding   → Bookings   → Discovery',
    },

    /* ---------------- Marketplace Operations ---------------- */
    {
      id: 'bookings', name: 'Bookings & Ops', facet: 'operations', autonomy: 'gated',
      mandate: 'Run the booking lifecycle end to end — reliably and within policy.',
      responsibilities: [
        'Process new bookings and hold inventory.',
        'Handle date / time changes and cancellations.',
        'Apply cancellation & refund policy consistently.',
        'Coordinate venue + required services into one confirmed order.',
        'Manage disputes with drafted, policy-grounded resolutions.',
      ],
      tasks: [
        'Confirm bookings and recompute totals on changes.',
        'Classify cancellations against policy.',
        'Assemble refund / credit proposals for approval.',
        'Coordinate services with Provider Network.',
        'Log dispute timelines and outcomes.',
      ],
      tools: ['Bookings DB', 'Calendar / inventory', 'Policy engine', 'Claude'],
      autonomyNote: 'Auto-handles confirmations, holds, and policy classification; refunds, goodwill credits, and customer-facing dispute messages require your approval (refunds are hard-gated via Finance).',
      escalations: [
        'Any refund or credit (approval).',
        'Cancellation inside the penalty window.',
        'A double-booking / inventory conflict.',
        'A dispute unresolvable by policy.',
      ],
      kpis: ['Booking completion rate', 'On-time confirmation', 'Dispute rate', 'Avg resolution time'],
      handoffs: '← Network   → Finance   → Trust & Safety   → Support',
    },
    {
      id: 'trust', name: 'Trust & Safety', facet: 'operations', autonomy: 'gated',
      mandate: 'Keep the marketplace safe, verified, insured, and compliant.',
      responsibilities: [
        'Verify host & provider identity and licenses.',
        'Confirm insurance coverage on venues and services.',
        'Screen transactions and accounts for fraud.',
        'Enforce required-service and permit rules.',
        'Manage suspensions and appeals.',
      ],
      tasks: [
        'Run identity / license checks at onboarding.',
        'Validate insurance certificates and expiries.',
        'Score transactions for fraud risk.',
        'Review flagged listings and users.',
        'Draft suspension / appeal notices.',
      ],
      tools: ['KYC / identity API', 'Insurance-cert validation', 'Fraud-scoring model', 'Document OCR', 'Claude'],
      autonomyNote: 'Auto-runs checks and risk scoring; suspensions, reinstatements, and any compliance / legal communication require your approval. Legal actions are hard-gated.',
      escalations: [
        'Failed identity / license verification.',
        'Expired or invalid insurance.',
        'Suspected fraud.',
        'Legal / regulatory notices or a safety incident.',
      ],
      kpis: ['% listings verified', 'Insurance-valid rate', 'Fraud caught vs missed', 'Time-to-verify'],
      handoffs: '← Onboarding   ← Bookings   → Finance',
    },
    {
      id: 'finance', name: 'Finance & Payouts', facet: 'operations', autonomy: 'hardgate',
      mandate: 'Move money correctly — collect, hold, pay out, reconcile, and report.',
      responsibilities: [
        'Capture renter payments and split platform fees.',
        'Schedule host & provider payouts on completion.',
        'Execute operator-approved refunds.',
        'Reconcile daily against the payment processor.',
        'Produce GMV, fee, and P&L reporting.',
      ],
      tasks: [
        'Authorize / capture on booking.',
        'Compute fee splits per order.',
        'Queue payouts for your approval.',
        'Execute approved refunds.',
        'Run daily reconciliation and reports.',
      ],
      tools: ['Stripe Connect', 'Ledger DB', 'Reconciliation engine', 'Reporting / BI'],
      autonomyNote: 'Auto-captures pre-authorized payments and produces reports; every payout, refund, and adjustment requires your approval — all money movement is hard-gated.',
      escalations: [
        'Every payout / refund (approval).',
        'A reconciliation mismatch.',
        'A failed payment or chargeback.',
        'A processor incident or negative-balance risk.',
      ],
      kpis: ['GMV', 'Fee revenue', 'Payout accuracy', 'Reconciliation variance', 'Chargeback rate'],
      handoffs: '← Bookings   ← Trust & Safety',
    },

    /* ---------------- Customer & Platform ---------------- */
    {
      id: 'support', name: 'Support', facet: 'customer-plat', autonomy: 'draft',
      mandate: 'Resolve renter, host, and provider questions fast — and escalate what it can\u2019t.',
      responsibilities: [
        'Answer inbound across email and chat.',
        'Triage by topic and urgency.',
        'Draft accurate, on-brand replies grounded in policy and booking data.',
        'Route operational issues to the right agent.',
        'Capture recurring feedback and gaps.',
      ],
      tasks: [
        'Classify and prioritize tickets.',
        'Draft replies with full booking context.',
        'Suggest macros for common cases.',
        'Hand off refunds → Bookings, fraud → Trust & Safety.',
        'Tag recurring issues for the team.',
      ],
      tools: ['Helpdesk', 'Claude', 'Knowledge base', 'Bookings / CRM context'],
      autonomyNote: 'Drafts every reply; customer-facing responses require your approval — or auto-send for a vetted FAQ set you explicitly enable. Routing and tagging are automatic.',
      escalations: [
        'Anything involving money, safety, or legal.',
        'Angry or at-risk customers.',
        'VIP hosts.',
        'Tickets it can\u2019t answer from policy.',
      ],
      kpis: ['First-response time', 'Resolution time', 'CSAT', 'Deflection rate'],
      handoffs: '→ Bookings   → Trust & Safety   → Finance',
    },
    {
      id: 'monitor', name: 'Workflow Monitor', facet: 'customer-plat', autonomy: 'auto',
      mandate: 'Watch the whole system and catch problems before they spread.',
      responsibilities: [
        'Detect funnel anomalies across supply, demand, conversion, and ops.',
        'Watch agent health and queue backlogs.',
        'Surface quality issues — bad reviews, SLA breaches.',
        'Run daily end-to-end health checks.',
        'Recommend concrete interventions.',
      ],
      tasks: [
        'Run hourly anomaly scans.',
        'Track each agent\u2019s throughput and error rate.',
        'Flag SLA and queue breaches.',
        'Compile the daily health digest.',
        'Open escalations with proposed fixes.',
      ],
      tools: ['Metrics / observability', 'Anomaly model', 'Reviews DB', 'Alerting'],
      autonomyNote: 'Fully autonomous — read-only observation, scoring, and alerting. Never acts on the business directly; it only opens escalations for you or another agent.',
      escalations: [
        'Any metric breaching threshold.',
        'An agent failing or stalling.',
        'A backlog building in the approval queue.',
        'A cluster of bad reviews.',
      ],
      kpis: ['Anomalies caught', 'False-positive rate', 'Mean-time-to-detect', 'System uptime'],
      handoffs: '→ all agents',
    },
  ];

  window.MANUAL = { FACETS, AGENTS, A };
})();
